### PR TITLE
Create AssemblyInfo.cs

### PR DESCRIPTION
**Pull request by ThebeRising**
I have tried to get a pipe running, it says this file is missing. Please check it against the source file to see if there are differences. As far as I can see, they all look the same.

### CODE REVIEW

**Comment by williamdewitt** [comment]
Could you please email a log file or screens hot of the error

**Comment by ThebeRising** [comment]
​

**Comment by ThebeRising** [comment]
The initial error was due to the update issue, the second is the missing
file...

**Comment by williamdewitt** [comment]
Change the banch in the pipeline configuration to ThebeRising-AssemblyInfo and see if it works

**Comment by ThebeRising** [comment]
I have looked through pipeline config, I cant see where to change the
branch...

**Comment by williamdewitt** [comment]
Edit the material. Options are type url and branch for git

**Comment by ThebeRising** [comment]
I see the error of my ways Sensei. I can actually use the branches before
they are merged, I am closer to my enlightenment!

**Pull request merged**
